### ISSUE TITLE
Mention that we discard unfactored discriminants

### ISSUE THREAD

**Issue by defeo** [defeo/hhs-keyex#1]
Concerning maximality of the endomorphism ring, Section 5.1 makes the point that it is "generically" easy to reduce to the maximal order. The "generically" is just footnote 3 on page 14, which is arguably very light.

We should be more precise in Section 4 and say that we discard a discriminant if we're not able to factor it (or, more precisely factor it up to Δ^⅓) and certify it has a large squarefree part. Factoring a random 1024 integer is not hard, and random quadratic discriminants even tend to be slightly smoother than random integers. It took less then one hour of GMP-ECM on 10 cores to factor the 512 bits discriminant.

Of course, we could be more lenient and say that it's ok to leave an unsmooth enough unfactored part, as it would be too expensive to evaluate the corresponding ascending isogenies.

**Comment by j-kieffer** [comment]
Commit name is "Closing issue #1 ?"
