### ISSUE TITLE
Better explain GHS algorithm

### ISSUE THREAD

**Issue by defeo** [defeo/hhs-keyex#20]
Reviewer said:

> p17: what is the purpose of stage 2?

The purpose is to represent the walk in polynomial space.

**Comment by abelian** [comment]
I think I may have clobbered your fix to this a few commits ago.  I'd rather not risk collateral damage in unwinding it all---would you mind checking/re-fixing?

**Comment by j-kieffer** [comment]
I think I didn't get the problem... the text is fine.

**Comment by defeo** [comment]
Both of your edits are in the HEAD, and they well complement each other.
