### ISSUE TITLE
Reformulate wishful thinking?

### ISSUE THREAD

**Issue by defeo** [defeo/hhs-keyex#21]
Reviewer said:

> p22-23: paragraph before section 5.4 looks a bit like wishful thinking to me

Not sure what to do with this

**Comment by abelian** [comment]
It _is_ wishful thinking, but I don't think we're implying anything stronger.  I'm OK with basically leaving this, though we could add some lame phrase to say "further investigation is required".

**Comment by j-kieffer** [comment]
I'm OK either way.
