### ISSUE TITLE
Better explain complex multiplication

### ISSUE THREAD

**Issue by defeo** [defeo/hhs-keyex#22]
Reviewer said

> p6: the definition of having CM by an order O seems to allow also for suborders, which would invalidate the class group formula

This is just a wording issue

> p6: the correspondence between ideals and isogenies does not take into account the inseparable part

We just say "extends to an action". We could be more explicit.

> p7: it would be simpler to make the dependency on t explicit by having
Ell_{q,t} so there is no confusion and no need to consider two components

We don't seem to agree with the reviewer.

**Comment by j-kieffer** [comment]
§1 and §2 are done.
For §3: is it necessary to obey each of the reviewers' remarks ? This one means a lot of rewriting, for uncertain interest to me.

**Comment by abelian** [comment]
Did you push your commits, Jean?  I don't see an update for either of the first two points.
(And no, we're not obliged to do everything they say.)

**Comment by abelian** [comment]
On reflection, I like their third suggestion a lot, but it would mean a lot of rewriting and redefining, and a lot of potential for introducing new mistakes.  I'd say we keep things the way they are, and switch to their suggestion next time we work on this (or a similar) problem.

**Comment by j-kieffer** [comment]
I believe that's the way it's written in the mémoire, but it wasn't very convenient either when I wanted to explain the twisting trick. The HHS paradigm requires one PHS, whereas we really work simultaneously on two isomorphic ones, and at the end the key is a j-invariant which is not an element in any of these two... It's better with some confusion !

**Comment by defeo** [comment]
I think the footnote to address §2 is wrong: a·E may be different if q is not prime. It is easier to say "let a be an invertible ideal of norm coprime to q", and then when we say "extend" be a bit more precise by saying something like "this can be extended to inseparable isogenies".

**Comment by j-kieffer** [comment]
Well, inseparable parts are simply powers of Frobenius, aren't they ? So the image curve does not change. For instance, take a = (π), then the φ_a we define is the identity (instead of π as it should), but the image curve is correct.

**Comment by abelian** [comment]
Inseparable parts are (isomorphic to) p-th powering maps, so you don't necessarily have the same image curve once you move to an extension of FF_p : you end up with a Galois conjugate instead.

**Comment by j-kieffer** [comment]
You're right, I forgot about non-prime fields.
I'll try to find a better formulation like what Luca said.

**Comment by defeo** [comment]
Maybe I'm typorigid, but I don't like putting footnote markers next to math formulas: φ⁸ can be interpreted as power, rather than a footnote marker. If I need the marker there, I prefer putting it after the punctuation mark, e.g. φ.⁸, otherwise better put it somewhere else next to a word.

**Comment by abelian** [comment]
After the punctuation mark is infinitely preferable.
