### ISSUE TITLE
Debunk reviewer's trick

### ISSUE THREAD

**Issue by defeo** [defeo/hhs-keyex#23]
Reviewer said:

> p11: even if the order of mu and lambda are the same (note that mu is
different from lambda), then you can still find eigenvectors easily by taking
a random l-torsion point P and computing Frob(P) - lambda*P which will give an
eigenvector corresponding to mu (and vice versa).

That is correct, but rather inconvenient. It makes implementation more complicated, and is very unlikely to apply in practice (it does not for any of the primes in our proposed curve).

**Comment by abelian** [comment]
Maybe as a footnote then?  "If the orders of lambda and mu are equal, then we can construct an eigenvector for lambda (resp. mu) by computing pi(P) - [mu]P (resp. pi(P) - [lambda]P).  This is not necessary for any of the primes in our proposed parameters."

**Comment by j-kieffer** [comment]
I just added this footnote.

**Comment by defeo** [comment]
I think the footnote would be better placed on the first paragraph of *Vélu steps*, like, after the end of the paragraph.

**Comment by j-kieffer** [comment]
Yes, I wondered where to put it, but then it would appear before the twisting trick which is more interesting and useful.

**Comment by defeo** [comment]
> but then it would appear before the twisting trick which is more interesting and useful.

That's why it's only a footnote, and not a remark. I feel putting the footnote near the twisting trick has two drawbacks:
- It is less relevant: the reviewer's trick really says something about what can be done to evaluate directions, even in an adverse case; the twisting trick, on the other hand, fabricates a favorable case.
- It clobbers the twisting trick, adding more info to something that's already hard to understand for the novice.

**Comment by abelian** [comment]
100% agreement with Luca.

**Comment by defeo** [comment]
I'm changing it, then.

**Comment by defeo** [comment]
Done. We just blew the 30 pages limit.
