### ISSUE TITLE
Review affiliations, add emails

### ISSUE THREAD

**Issue by defeo** [defeo/hhs-keyex#27]
From the [Springer guidelines](ftp://ftp.springernature.com/cs-proceeding/svproc/guidelines/Springer_Guidelines_for_Authors_of_Proceedings.pdf):

> The  affiliated  institutions,  including town/city and country, are to be listed directly below the names of the authors. Multiple affiliations should be marked with superscript Arabic numbers, and they should each 
start  on  a  new  line.  Including  your  postal  code  is  optional.  We  encourage  authors  to include their ORCIDs in superscript next to their names (see Sect. 3.4 for details).  
> Please  place  an  envelope  icon  (or  any  other  pointer)  next  to  the  name  of  the  corresponding  author,  whose  email  address  is  mandatory,  in  the  header  of  the  paper.  Email addresses should start on a new line directly under the corresponding affiliation. 
> We strongly recommend that all authors include their email addresses in their papers. [...]

- [ ] Add Jean's affiliation at Bordeaux.
- [ ] Technically, Jean was also affiliated with Saclay during this work.

**Comment by j-kieffer** [comment]
My email address expires next year, but it's still better than gmail, isn't it ?

**Comment by defeo** [comment]
1. Don't you have a @normalesup.org address?
2. Don't you have an @inria.fr address? Inria's pretty lame, I think they will expire the address after the PhD, but still.
3. Don't you have an @u-bordeaux.fr address? That's probably going to be yours for life.

At any rate, I'm not sure emails are very important. The Springer guidelines insist on them, but the IACR guidelines don't, and we already gave Springer our emails and a corresponding author anyway, so these are probably in the metadata.

Affiliations are more important, so that all your employers are happy. FTR, this is what I gave the PC chairs afew weeks ago:

> Luca De Feo¹³, Jean Kieffer²³⁴, and Benjamin Smith³
> 
> ¹ Université Paris Saclay, UVSQ, LMV, Versailles, France
> ² École Normale Supérieure, Paris, France
> ³ Inria and École polytechnique, Université Paris Saclay, Palaiseau, France
> ⁴ IMB - Institut de Mathématiques de Bordeaux, Inria Bordeaux - Sud-Ouest, Talence, France

**Comment by j-kieffer** [comment]
1. No(t yet) 2. Yes 3. Not yet
Your formulation is great, but it seems difficult to add email addresses, so maybe we could just omit them.

**Comment by abelian** [comment]
I've pushed a suggestion that includes emails (Jean, you'll need to fill yours in).  See what you think.

**Comment by j-kieffer** [comment]
I can't see your commit...

**Comment by j-kieffer** [comment]
Anyway, I think my email address could be @math.u-bordeaux.fr, since it will exist when the conference starts.

**Comment by abelian** [comment]
Sorry, shut down my session before the push actually happened...  But you get the idea.  Replace the "jean's email..." with your email, and move it to a line on its own with the matching institution.

**Comment by j-kieffer** [comment]
I think it's fine now.
