### ISSUE TITLE
Algorithms in Section 3.2

### ISSUE THREAD

**Issue by abelian** [defeo/hhs-keyex#3]
We need to clarify/formalize the algorithms VeluStep (since it's the heart of the main result) and ElkiesStep (to enable a clear comparison with VeluStep).

I think this means making each into an actual Algorithm X.  Steps like IsogenyFromKernel, etc., can be left as subroutines.

**Comment by j-kieffer** [comment]
I commited my changes, but maybe you want to read them before closing this issue.
