### ISSUE TITLE
Organisation of \S3.2

### ISSUE THREAD

**Issue by abelian** [defeo/hhs-keyex#4]
Maybe reorganise into
1. How to compute an isogeny (ElkiesStep and VeluStep)
2. How to compute a walk (ie, a big smooth isogeny), and the cost of different walks using our algorithms
3. How to choose keys appropriately
?

At the moment this is all mixed in together, and the reader has to kind of guess what we're going to do before we end up doing it.

**Comment by j-kieffer** [comment]
I commited my changes, but maybe you want to read them before closing this issue.
