### ISSUE TITLE
Rework introduction

### ISSUE THREAD

**Issue by j-kieffer** [defeo/hhs-keyex#7]
Be more direct about the goal of the paper: new algorithm showing that the Ros.Stolb. cryptosystem can be used in practice
Give (subset of) timings: practical usefulness made clear
i.e. give people reasons to read the 30 pages
don't speak about NIST ?

**Comment by j-kieffer** [comment]
+ we give security proofs for the non-unif. distribution

**Comment by abelian** [comment]
We also need to fix the definition of PHS: at the moment we're saying that g \mapsto g.x should be an isomorphism of G and X.  But G is a group and X is a set, so "isomorphism" is not defined, unless

- we're talking about an isomorphism of sets, which is just a bijection, but this isn't a strong enough condition (I think); or
- we're talking about an isomorphism of G-sets, but then I'm not sure if that's correct either...

Either way, we're not exactly making anything more accessible for the reader.  We might have to cart out the old "simple transitive" boilerplate here, unless anyone can think of a more elegant expression.

**Comment by defeo** [comment]
Isn't 

- G is a group acting on X, and
- φ_x is a bijection for any x.

an equivalent definition for a PHS? Wikipedia uses exactly this one https://en.wikipedia.org/wiki/Principal_homogeneous_space

**Comment by abelian** [comment]
Not _exactly_: they use the more usual definition that (x,g) \mapsto (x,g.x) is an isomorphism X x G -> X x X.  Which seems to be equivalent to what we have in the case where G is a finite group and X is a finite set, which is good.  I don't think that equivalence works in more general settings though (which is maybe what got me worried...  I had to puzzle through a bunch of this stuff for schemes way back when).

**Comment by defeo** [comment]
Oh, yes. If you're asking from some topological properties, e.g. continuity, then yes, that's not the same.

But for sets, even infinite, I don't see what could go wrong (assuming axiom of choice, maybe).
