### ISSUE TITLE
Quantum security

### ISSUE THREAD

**Issue by j-kieffer** [defeo/hhs-keyex#8]
Is the quantum safeness argument valid ?
Agree with CSIDH on these questions ?
(I personally lack background on this)

**Comment by j-kieffer** [comment]
Should we leave this section as it stands now ? The reviewers made no remark about it, and the research is still active, I think.

**Comment by defeo** [comment]
CSIDH was asked to revise its parameter sizes, but I don't know exactly how they are going to change them. Even if we changed them, we'd probably end up with different numbers.

Given Xavier & André do not directly target us, and that the reviewers didn't ask us to act, I think it is best to leave them as is.

**Comment by j-kieffer** [comment]
OK, closing this one.
